### ISSUE TITLE
grammar/type_system : change test of non-empty strings

### ISSUE THREAD

**Issue by BenGardiner** [strictdoc-project/strictdoc#1210]
Our build for https://github.com/nmfta-repo/vcr-experiment was 'broken' by https://github.com/strictdoc-project/strictdoc/commit/c71d40db2debad875accb533931919d8e7fec979

for two reasons
1. we did have _some_ empty multi-line strings (now fixed https://github.com/nmfta-repo/vcr-experiment/commit/8c8b6cb2d0798dec5c0229af98a26a0085e8a696) AND
2. we have some multi-line strings which start with RST indentation e.g. to have block quotes in `PUB_REFS` https://github.com/nmfta-repo/vcr-experiment/blob/8c8b6cb2d0798dec5c0229af98a26a0085e8a696/01_gateways.sdoc#L170

I think the intentions of https://github.com/strictdoc-project/strictdoc/commit/c71d40db2debad875accb533931919d8e7fec979 are good. No argument from me with being strict(er) about empty single- or multi-line strings in strictdoc documents. The problem here, IMO, is the inference `// Both must start with a non-space character.` @ https://github.com/strictdoc-project/strictdoc/blob/c71d40db2debad875accb533931919d8e7fec979/strictdoc/backend/sdoc/grammar/type_system.py#L8

I believe that strictdoc needs to permit leading spaces in multi-line strings to allow for RST formatting such as block quote.

I have some proposed changes to fix this issue as well.

**Comment by stanislaw** [comment]
Thanks for contributing this change!

It looks like you are building directly from source code, so you don't need a new Pip package, correct?

---

Regarding the communication channels: in fact, I was thinking that I could break something for existing users, but I decided to go ahead and see if someone notices it. Do you think I should set up a channel for communicating changes (sometimes these changes have to happen...)? How would you prefer to be notified? Some people are on the Discord group, some are active here from time to time, and some communicate with me exclusively via email.

Some options I have in mind: a newsletter, a mailing list, quarterly blog posts. Do you think any of these could work for you?

**Comment by BenGardiner** [comment]
> Thanks for contributing this change!

It's my pleasure!
 
> It looks like you are building directly from source code, so you don't need a new Pip package, correct?

Yep we are taking HEAD of main.

> Regarding the communication channels: in fact, I was thinking that I could break something for existing users, but I decided to go ahead and see if someone notices it. Do you think I should set up a channel for communicating changes (sometimes these changes have to happen...)? How would you prefer to be notified? Some people are on the Discord group, some are active here from time to time, and some communicate with me exclusively via email.

I've added a nightly build to CI at https://github.com/nmfta-repo/vcr-experiment/blob/main/.github/workflows/publish.yml which should keep us more informed. 

I think the problem wasn't borne from a lack of notice but rather a lack of attention on my part -- I should have been paying closer attention to the project. 

> Some options I have in mind: a newsletter, a mailing list, quarterly blog posts. Do you think any of these could work for you?

I think it's reasonable for users to read the release notes for break changes and similar. If you were going to take on more communication work -- and you don't have to -- a quarterly blog would be fine by me.

Thank again @stanislaw and @mettta for all the work you do!

**Comment by stanislaw** [comment]
> I've added a nightly build to CI at https://github.com/nmfta-repo/vcr-experiment/blob/main/.github/workflows/publish.yml which should keep us more informed.

I do the same for StrictDoc because its upstream Pip dependencies sometimes change, breaking the build.

> I think the problem wasn't borne from a lack of notice but rather a lack of attention on my part -- I should have been paying closer attention to the project.
> 
> > Some options I have in mind: a newsletter, a mailing list, quarterly blog posts. Do you think any of these could work for you?
> 
> I think it's reasonable for users to read the release notes for breaking changes and similar. If you were going to take on more communication work -- and you don't have to -- a quarterly blog would be fine by me.

Thanks for the feedback!

> Thanks again @stanislaw and @mettta for all the work you do!

👍 

---

> MULTILINE_WORD_THRESHOLD = 6

It's been a while since I wanted to discuss another breaking change with you. Remember, we introduced this threshold parameter to decide whether a field should be treated as single-line or multiline?

Due to some web user interface implementation details, @mettta and I found it easier to decide on single-/multi- statically as follows:

```
        title_field_index = grammar_field_titles.index(
            RequirementFieldName.TITLE  # STATEMENT is another candidate because it is the most mandatory field in any grammar, whatever custom it is.
        )
        if field_index <= title_field_index:
            # field is single-line
        else:
            # field is multiline
```

We found it much easier to reason about this and implement: by convention, all single-line fields are those that are placed about the TITLE field in the grammar and the multiline fields are everything after `TITLE`. We are quite certain that it simplifies things for us but I wanted to confirm with you that your existing setup will tolerate this change if we remove the `MULTILINE_WORD_THRESHOLD`-based decision from the code.

Please confirm.

**Comment by BenGardiner** [comment]
Hi @stanislaw,

Understood and no problem. I checked our two strictdocs' grammars and in both cases all the multi-line fields are after TITLE. We will need to move a couple single-line fields to above the TITLE in the grammar (https://github.com/nmfta-repo/vcr-experiment/issues/54) but otherwise this should be a perfectly fine heuristic.

**Comment by stanislaw** [comment]
Ok, thanks for confirming this. I will change it soon (within this weekend).

**Comment by BenGardiner** [comment]
> Ok, thanks for confirming this. I will change it soon (within this weekend).

My pleasure. Our main branch is ready now; so you should be able to check the nightly here for failures https://github.com/nmfta-repo/vcr-experiment/actions/workflows/publish.yml

**Comment by stanislaw** [comment]
A small update here: I have decided to rely on the position of the `STATEMENT` field, not TITLE, because I consider the statement field to be the most used/present of all requirement fields, on average. This led me to require any custom grammar to include a STATEMENT field, even if it's `REQUIRED` parameter is `False`.

This convention of `<STATEMENT` for single-line and `>STATEMENT` for multiline simplifies my life quite a bit. I hope that it will not create any severe limitations for anyone 🤔 

I will document this in the user guide and my next doc cycle.

**Comment by BenGardiner** [comment]
I think that still makes sense to me; no objections. And the changes we made in https://github.com/nmfta-repo/vcr-experiment did move the single line things above STATEMENT as well as TITLE so we are prepared.
