### ISSUE TITLE
Bug: Editing text via web ui deletes Refs Type File and Refs Value

### ISSUE THREAD

**Issue by MartyLake** [strictdoc-project/strictdoc#1319]
Hello

# Instructions
```
git clone git@github.com:strictdoc-project/strictdoc-examples.git
cd strictdoc-examples
strictdoc server .
```
navigate to http://127.0.0.1:5111/strictdoc-examples/examples/example_08.html
click on EDIT for section `1. Whole file reference`
modify text by adding `lorem ipsum`
click on SAVE
# Expected
```
$git diff
diff --git a/examples/example_08.sdoc b/examples/example_08.sdoc
index 4644b87..277433f 100644
--- a/examples/example_08.sdoc
+++ b/examples/example_08.sdoc
@@ -7,7 +7,9 @@ REFS:
 - TYPE: File
   VALUE: examples/example_source_files/file.py
 TITLE: Whole file reference
-STATEMENT: This requirement references the whole file.
+STATEMENT: >>>
+This requirement references the whole file. lorem ipsum
+<<<
 
 [REQUIREMENT]
 UID: REQ-002

```
# Actual
```
$git diff
diff --git a/examples/example_08.sdoc b/examples/example_08.sdoc
index 4644b87..9023420 100644
--- a/examples/example_08.sdoc
+++ b/examples/example_08.sdoc
@@ -3,11 +3,10 @@ TITLE: Example 8: Traceability between requirements and source files
 
 [REQUIREMENT]
 UID: REQ-001
-REFS:
-- TYPE: File
-  VALUE: examples/example_source_files/file.py
 TITLE: Whole file reference
-STATEMENT: This requirement references the whole file.
+STATEMENT: >>>
+This requirement references the whole file. lorem ipsum
+<<<
 
 [REQUIREMENT]
 UID: REQ-002
```

**Comment by stanislaw** [comment]
Thanks for reporting this! You are hitting something that has not been implemented yet :(

Previously, editing the File-based links was not supported in the UI but the whole linking mechanism is being reworked right now and editing of Parent/Child/File links will finally work. There are many edge cases that have to be handled, see here:

https://github.com/strictdoc-project/strictdoc/issues/1310

**Comment by stanislaw** [comment]
For now, editing any document without File links should work properly.

**Comment by MartyLake** [comment]
Thanks for your answer!

Alright then, I will wait for future releases !

**Comment by stanislaw** [comment]
As a side note: the traceability with requirements and files has been with a low priority so far because 1) it needs much more work to reach the production state and 2) there was not much interest from the user community to this specific feature.

I would be curious to know if you are/were looking to just text-based requirements management creation or you specifically want the requirements traceable to the source files? Any insights are appreciated :smile:

**Comment by MartyLake** [comment]
@stanislaw Thanks for asking! 

I think that text-based requirements management is a way to get better software, and I want to try it out on some toy project in my personal time, but I don’t know where and how to learn it.

I am discovering the whole field of requirements engineering and testing tools on my way there. I am just exercising all the options offered by software, with the assumption that these options exist because the existing users are needing them, so I find your message very very valuable!

**Comment by villanella** [comment]
Hello! How can I reference to yaml source code (for example, Ansible roles etc)?
It seems that yaml extension is excluded, because I get the error "requirement references a file that does not exist" when I reference to yaml file.

**Comment by stanislaw** [comment]
In the newly released version https://github.com/strictdoc-project/strictdoc/releases/tag/0.0.45, the file links are still not editable in the UI (a warning message is printed), but editing the normal relations should no longer remove the File links. I will close this issue because the bug itself should be fixed. The missing implementation part is tracked here: https://github.com/strictdoc-project/strictdoc/issues/1350.

**Comment by mtt-ableton** [comment]
Can confirm latest release fixes the bug.
