### ISSUE TITLE
Ability to interact with requirements programatically

### ISSUE THREAD

**Issue by richardbarlow** [strictdoc-project/strictdoc#1378]
We love using strictdoc because it means that our requirements are captured in a form that is easy to version. Another aspect to them being in this form is that it opens up the possibility of us interacting with the requirements programatically, since they are in a machine-readable format.

We appreciate that there is currently no (that we know of) python API to enable the tree of requirements to be loaded in and queried/traversed. For now we have got by by exporting to excel with all fields and then reading these files in with a few lines of python and reconstructing a data structure to allow us to query the data. At the moment we use this to automatically generate some verification and validation check lists from our V&V 'requirements'. At some point we would like to start to implement some custom tests (e.g. that all requirements trace to a validation procedure), but we have not started that work yet.

Unfortunately, with the recent change to a 'RELATIONS' section, instead of a 'REFS' field our approach of exporting to excel files has been broken. Since the RELATIONS are no longer fields, it is not possible to include them in the excel file using the `--fields` argument to `strictdoc export`. With the additional functionality that the RELATIONS section introduces I can see that this would be hard to implement well.

The reality is that our use case really needs an API instead of us bodging a solution via excel files. Ideally this would be a python API, since we will always have strictdoc installed and we already use python for automation.

Even if we move away from using the excel files in this way, I can imagine that there might be other users who were dependent on the REFS field in the excel exports and will have an issue with there being no way of including the RELATIONS.

**Comment by richardbarlow** [comment]
I should say that we'd be happy with an unstable API and can adapt our code if it changes with each strictdoc release. I appreciate that designing and maintaining a stable API is a big undertaking and something that you might not be looking to support right now, however we're willing to adapt as necessary if it gives us the flexibility that we need.

**Comment by stanislaw** [comment]
What you are reporting about Excel is most probably a missed regression, which I am now tracking here: https://github.com/strictdoc-project/strictdoc/issues/1379.

Your question about the Python API makes complete sense, and here is what I have to offer right now:

- An 'official' API does not exist, but you may use the example of the `SDWriter` class, which exercises the complete export of the Python data objects to the SDoc format. Since, the SDoc format is the primary data format, the SDWriter is quite "feature-rich" in what it does and covers. The `RSTWriter` is less powerful because it does not reflect the full data model, but is probably worth a look as well.
- `strictdoc/backend/reqif/p01_sdoc` has exporter/importer routines for the ReqIF format. There you could also see that the very same core classes from the Python data model, e.g. Requirement, Section, Document, Grammar, etc. are created or read from and to the ReqIF format.
- One class that is used to simplify some requirements creation procedures is `SDocObjectFactory` but I must admit that its interface is very ad-hoc and has not been designed to serve as a general API building block.

> I should say that we'd be happy with an unstable API and can adapt our code if it changes with each strictdoc release. I appreciate that designing and maintaining a stable API is a big undertaking and something that you might not be looking to support right now, however we're willing to adapt as necessary if it gives us the flexibility that we need.

Having the above said, if you master the work with the Python data model classes like StrictDoc itself does it, you should become as stable as StrictDoc is. There should be changes from time to time, such as this one with REFS->RELATIONS, but as I said in the other ticket, I am looking into improving how the announcements and news are communicated to the slowly growing community of StrictDoc's users.

Let me know if these pointers are a good start. We can certainly consider creating more encapsulated facade-like classes but for StrictDoc's needs, working with the data objects directly has been the most straightforward.

**Comment by stanislaw** [comment]
A new day with new thoughts. I have updated my comment above with some new information.

**Comment by richardbarlow** [comment]
Thanks for all of the info! I've converted our process over to using the TraceabilityIndex and it works perfectly :smile:

There was a fair bit of boilerplate required to get to the point of being able to iterate over the documents/requirements, but now it's working that's not really a problem. Also, it may just be because I'm missing something (I copied how the ManageAutoUIDCommand is implemented, which may not be the most efficient approach).

**Comment by stanislaw** [comment]
I have documented some of my answers here in the doc: https://strictdoc.readthedocs.io/en/latest/strictdoc_01_user_guide.html#python-api. It is not perfect but at least some pointers. It would be great to improve the Python API over time, and we will do so as we get more user requests.
