### ISSUE TITLE
Documentation: List of `DOCUMENT` grammar elements does not specify where `REQ_PREFIX` belongs

### ISSUE THREAD

**Issue by KlfJoat** [strictdoc-project/strictdoc#1670]
The StrictDoc grammar is positional. While that is kind of limiting, it's generally okay because the documentation makes it clear what elements go in which order.

But that's not the case for `REQ_PREFIX`, as I found out when I tried using it at the `DOCUMENT` level.

In the [list of `DOCUMENT` grammar elements](https://strictdoc.readthedocs.io/en/stable/strictdoc_01_user_guide.html#document), `REQ_PREFIX` is not listed. So it's unclear where it goes in the order.
https://github.com/strictdoc-project/strictdoc/blob/590aaf1c4342d381329b2f965e7659acd6b451e8/docs/strictdoc_01_user_guide.sdoc#L503-L530

In [the only 2 mentions of `REQ_PREFIX` in the documentation](https://strictdoc.readthedocs.io/en/stable/strictdoc_01_user_guide.html#automatic-assignment-of-requirements-uid), it is shown as ordered immediately after the `TITLE` element of both the `DOCUMENT` section and `SECTION`... section. 
https://github.com/strictdoc-project/strictdoc/blob/590aaf1c4342d381329b2f965e7659acd6b451e8/docs/strictdoc_01_user_guide.sdoc#L1908-L1920

So I placed it after `TITLE` for `SECTION` headings, and it worked. But I got an error when I put it after `TITLE` for the `DOCUMENT` heading. The `grammar.py` file shows that for `DOCUMENT` headings, it belongs between `CLASSIFICATION` and `ROOT`.
https://github.com/strictdoc-project/strictdoc/blob/590aaf1c4342d381329b2f965e7659acd6b451e8/strictdoc/backend/sdoc/grammar/grammar.py#L152-L158 

Sure enough, that solved my problem.

Please update the documentation to match the grammar definition for usability purposes...  or don't be quite so strict with element placement and order. (I know, unlikely, but it *IS* an acceptable resolution to my issue :smile: )

**Comment by stanislaw** [comment]
Hi @KlfJoat, thanks for reporting this. There are several issues here:

- I proposed a nice addition to Arpeggio parser that would guide you to find the fields order much quickly but unfortunately the patch was not accepted due to this case being too specific to StrictDoc: https://github.com/textX/Arpeggio/pull/114. (Arpeggio is a PEG parser behind textX.). If this was implemented, the error message for an incorrectly placed grammar field would show you which options you actually have when doing something incorrectly with the grammar.
- The requirements order is fixed due to the grammar which fixes the elements order and then the UI writes them in the order as configured.
- I think there is nothing serious that prevents us from relaxing the order for the document options. It is something that you could do relatively soon. I will give this some more thought and decide whether I do it, right now it seems reasonable.

The documentation fix is on the way: https://github.com/strictdoc-project/strictdoc/pull/1672 which should resolve the main topic of your report.
