### ISSUE TITLE
Reusing glossary entry across multiple documents in same doctree?

### ISSUE THREAD

**Issue by gregshue** [strictdoc-project/strictdoc#1779]
I am trying to create a glossary entry for use across multiple documents within the same instance of `strictdoc server`. I ran into the error 

> "[DOCUMENT_FROM_FILE]: A multiple inclusion of a document is detected. A document can be only included once: $relativePathToFileFromDetectedFileLocation".

Details:

- The fragment file contains only document header and a single glossary entry captured within `[FREETEXT]`.
- I included this in the following files:
  - `glossary/index.sdoc`
  - `software_requirements/glossary.sdoc` 
- I am running Strictdoc v0.0.54 on Ubuntu 22.04 (upgraded).

How am I supposed to reuse a glossary entry across multiple StrictDoc documents?

**Comment by stanislaw** [comment]
Including one fragment into multiple documents is not as trivial as it could seem.

If an included fragment has nodes with UIDs in them, it is not clear yet how to make a consistent traceability graph because the UIDs must be unique.

For this specific simpler case of a glossary, I have relaxed the validation, and it is now possible to include a document into multiple documents under the condition that the included document is free from any traceable nodes.

Please try a new `0.0.55a1` with `pip install strictdoc --pre`, where this should work now.
