### ISSUE TITLE
RFC: Assessing impact of a clarified requirement?

### ISSUE THREAD

**Issue by gregshue** [strictdoc-project/strictdoc#1806]
This is NOT a feature request. It is just an exploration discussion of a User Need.

As a system evolves it may grow to cover a larger context. Requirement statements may need to change text in order to retain their original meaning/scope. All existing requirements tracing to that changed statement need to be reassessed to see if the tracing still holds or their statement text also needs to be changed.

Thoughts?

**Comment by stanislaw** [comment]
The idea here was to implement a VERSION field on both a requirement node and its RELATIONs.

Let's say your node REQ-1 has `VERSION: 1` and there is another node B that has a `UID: REQ-2` and `RELATIONS: UID: REQ1`/`VERSION: 1`.

Now, you modify your requirement REQ-1 and bump its VERSION to 2. This will make the tool highlight you automatically that the REQ-2 now points to REQ-1 with an outdated link (because its version is still 1).

I myself didn't have time to think about this properly, I simply saw how the OpenFastTrace tool does it, so the credit for this approach goes to them.

The advantage of this approach is that you get very nice impact assessment, the disadvantage is that you have to maintain the versions everywhere if you want to implement this to 100%.

It is rather easy to implement this in StrictDoc, but we were blocked by some other ongoing issues like Composable Documents or recent ReqIF upgrades.

cc @kestewart @redcatbear

**Comment by gregshue** [comment]
@stanislaw Before I share other thoughts, would you prefer this topic move to Discussions?

**Comment by stanislaw** [comment]
> @stanislaw Before I share other thoughts, would you prefer this topic move to Discussions?

It is not important that much but let's move it to Discussions and continue there.
