### ISSUE TITLE
Bug: Assert on C++ parsing

### ISSUE THREAD

**Issue by johanenglund** [strictdoc-project/strictdoc#2026]
## Describe the bug

The following construct seems to be the last thing that trace to source asserts on in my current code base. It's only when returning a reference for the operator, otherwise operators works well.

```
class Foo
{
    int a_, b_;

   public:
    Foo() {}
    Foo(int a, int b) : a_(a), b_(b) {}
    Foo& operator+(const Foo& c);
};

Foo& Foo::operator+(const Foo& c) { return *this; }
```

Also, maybe it would be a good thing if the assert always show filename and row number for the problem? Would ease future troubleshooting.

**Comment by stanislaw** [comment]
The fix is on the way: https://github.com/strictdoc-project/strictdoc/pull/2027.

> Also, maybe it would be a good thing if the assert always show filename and row number for the problem? Would ease future troubleshooting.

I enabled this for now. However, Python asserts have a serious impact on performance, especially if the asserts have form:

```
assert(cond, debug_string)
```

The problem is that all debug strings get expanded whether or not the assert is hit.

I don't know how tree-sitter works but it could be that for printing the text nodes it actually assembles the strings from multiple nodes.

A less hacky implementation would be to do proper exception handling:

```
if (!condition) {
  raise exception(printable stuff)
}
```

then only the failed branches will trigger the evaluation of debug strings. I will stick with asserts for the first versions of this code and then gradually move to proper ifs.

**Comment by stanislaw** [comment]
> The following construct seems to be the last thing that trace to source asserts on in my current code base. It's only when returning a reference for the operator, otherwise operators works well.

I currently don't have access to a C++ codebase to test everything, so we have to implement this gradually based on your feedback at the moment. Hopefully, it is not too many cases that need to be handled. I could expect some fun with the C++ templates, we will have to do something about them.

**Comment by johanenglund** [comment]
Great! I'll try this out and keep you updated as the code base grows :)
