### ISSUE TITLE
HTML distribution as one file

### ISSUE THREAD

**Issue by stumpyfr** [strictdoc-project/strictdoc#279]
To enable easier sharing, especially with none technical audience, it's would be great to be able to export the HTML as one file containing everything.

Making the sharing and opening of it as simple as possible for any type of audience.

**Comment by stanislaw** [comment]
Interesting feature request. Would you describe it a bit more?

Is it about merging all HTML files into one and creating a table of contents that references all documents and their sections?

Which view should it be based on? On "document" or "table" view? Or some new representation?

I assume that the CSS styles should be embedded right into the HTML to not have to deal with external assets. Is this also something that you are considering?

Just a side note: I haven't explained this in the docs but exporting complete documentation into one PDF is possible with Sphinx. It does that automatically when you pass it a number of RST documents.

**Comment by stumpyfr** [comment]
yes, having only one "large" .html, ready to be shared with people.
Best would be able to have different views, each one is useful but at least the "document" yes.
and yes, no external assets, the idea is to be able to send this html by email, for example, double click on it and it's working.

Yes, I tried the pdf export. It's working but losing the "nice" representation of the HTML one.

**Comment by stanislaw** [comment]
The most straightforward and therefore fastest implementation I could think of would be to simply concatenate all `*.sdoc` files into one SDoc file and let it go through the normal HTML export pipeline.

There are a few questions that have to be solved on the way:

1) Does the order in which the docs have to be concatenated matter? I assume you want to control this and the easiest solution is to control it on a file name level: an sdoc named `01-ABC.sdoc` will go before `02-DEF.sdoc`, etc.

2) How to do with the concatenation of table of contents? If the document is the fourth on the list of documents, and it has a chapter level 1 `Hello world`, will it be displayed as `1 Hello world` on the TOC or as `4.1 Hello world`? I think, I would prefer to avoid shifting of the TOC levels. Instead, a concatenation of single documents TOCs split by the document names could be done. What are your thoughts?

3) How would you name this aggregated document? Any suggestions?

**Comment by stumpyfr** [comment]
I am currently using only one `.sdoc`, the idea is really to embed all the assets and page into one HTML file.
in the case of multiple `.sdoc`, your ideas 1 and 2 make sense to me.
about 3, a simple `export.html` would make sense, with maybe a cli optional argument to override.

**Comment by stanislaw** [comment]
Continuing discussion: (if it is about one .sdoc file) Do I understand it right that the current document view would work for you with the following modifications:

1) You just don't want the surrounding panels, such as the one with `DOC`, `TBL`, `TR`, `DTR`, and "Table of Contents/To Index"

2) Is it ok to still have a two-column layout with the left column to be the Table of Contents and the right to be the doc like it is now?

3) Embedded assets should, of course, be doable. Any other differences you could indicate?

P.S. I am trying to collect feedback from you in order to decide if a JavaScript-rich functionality should be introduced or this `standalone export` feature could be implemented without too much JS involved. For one thing, I don't see an easy way to combine all types of documents into a single document without having a layer of JS code controlling the layout.

**Comment by stumpyfr** [comment]
1. each type of view (DOC, TBL,...) has an advantage, best would be to keep them in the standalone file, yep would require some JS.
2. same layout as currently, TOC on the left and content on the right
3. nop, pretty sure we can find a python package already "merging" static assets

**Comment by stanislaw** [comment]
I am discussing this further with @mettta now.

Thanks to the quite modular CSS structure, we can generate 4 types of documents into a single file and then switch between them using an additional bit of JS. The feature will only work for single sdoc files and will be enabled with the `export --standalone` flag.

I think I could suggest a first version in 3-5 days. @mettta and I know that there is some specific CSS and Jinja work that will have to do as well.

> nop, pretty sure we can find a python package already "merging" static assets

@stumpyfr do you have a specific package in mind already?

**Comment by stumpyfr** [comment]
I don't know any package for that, will have a look

**Comment by stanislaw** [comment]
I have considered creating a single standalone file that merges all 4 document types and decided to not implement it because of the additional complexity that such an implementation would require.

Please check [this](https://github.com/strictdoc-project/strictdoc/tree/standalone) branch: for now, I am only generating the "document view" in the standalone mode. Only CSS and JS assets are embedded and there is no `--standalone` key.

Let me know if this works well for you.

**Comment by stanislaw** [comment]
I went ahead and implemented the standalone export under `--formats=html-standalone` flag. The implementation is already in master.

Let me know if this works well for you.

**Comment by stanislaw** [comment]
The documentation has landed: https://strictdoc.readthedocs.io/en/latest/StrictDoc.html#standalone-html-pages-experimental.

**Comment by stumpyfr** [comment]
LGTM :)

**Comment by stanislaw** [comment]
Great! I will close this one then.
