### ISSUE TITLE
Option: enable strict mode: turn warnings into errors

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#451]

**Comment by richardbarlow** [comment]
This is something that we'd really appreciate being implemented, if at all possible. Right now we build our documentation in GitHub Actions and we rely on the fact that we build PDFs via Sphinx to catch issues such as invalid references. It's good enough for that use case. However, it means that the feedback loop for local development is slower than we'd like.

Ideally we'd have strictdoc run automatically whenever any of the source files are modified (this is something we can easily handle ourselves and don't need any special features in strictdoc to support this) and exit with a non-zero exit code whenever it encounters any issues (warnings or otherwise). In general I'm not a fan of maintaining any sort of code-base with warnings present and therefore always treat warnings as errors where possible. Being able to do this with strictdoc would make our lives much better and save us quite a bit of time.

**Comment by richardbarlow** [comment]
I think treating warnings as errors by default would be great. It feels in keeping with the 'strict' in the name of the project :smile: 

I agree that separating the logging and reporting of the issues would be a good approach. It keeps the reporting consistent and keeps thing flexible for future enhancement, such as outputting machine readable errors (for IDE support) and to allow the user to select if the command fails on the first error encountered, or if it continues to completion (if possible) and report all errors at the end.

**Comment by stanislaw** [comment]
I went ahead and converted all warnings to errors without introducing any options to disable such a strict behavior.

https://github.com/strictdoc-project/strictdoc/pull/1197

The [latest 0.0.42 Pip](https://pypi.org/project/strictdoc/) has been released.
