### ISSUE TITLE
Option: support two types of documents: requirements with titles and requirements with no titles

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#462]
Currently, StrictDoc shows `[no title]` when no title is provided for a requirement.

This limits the support of the documents where the title is never used. Example: NASA cFS SCH documentation. In that case, a more consistent behavior would be to show a requirement's UID as a title.

**Comment by stanislaw** [comment]
Related issue: #365.

**Comment by gioboske** [comment]
Hi, is there any update on this issue?
I'm dealing with some (quite huge) set of documents where titles are not used.

Thanks

**Comment by gioboske** [comment]
> [...] In that case, a more consistent behavior would be to show a requirement's UID as a title.

In addition, it could be useful to make possible to leave a requirement with no title at all and to implement a similar strategy as per #639 for sections (`LEVEL: None` option) in order to remove the requirement's title numbering.

**Comment by stanislaw** [comment]
I am ready to discuss this deeper.

> I'm dealing with some (quite huge) set of documents where titles are not used.

Can you give me an example of such a document available on the internet (or maybe just a screenshot if easier and at all possible)? Your requirements do not have titles, but do they have UIDs? 

Currently StrictDoc shows a requirement's UID in the TOC if the requirement does not have a title. Is this behavior acceptable or you want to remove it from TOC completely?

I am checking this now in the current StrictDoc's UI - if I completely remove the title from the requirement template (`h_title.jinja.html`), the template does not look great, this is why I would like to see your example to get an idea of how we should present this UI-wise (this is where I might again ask @mettta for help).

**Comment by stanislaw** [comment]
cc @mettta

**Comment by gioboske** [comment]
Hi @stanislaw,
sorry for my late reply. I'll try to provide some details of my use case in the following.

> > I'm dealing with some (quite huge) set of documents where titles are not used.
> 
> Can you give me an example of such a document available on the internet (or maybe just a screenshot if easier and at all possible)? Your requirements do not have titles, but do they have UIDs?

Unfortunately, I cannot share the actual documents I'm working on, due to some intellectual property issues (by the way, the documents I'm dealing with refer to system and SW requirements in the railway fields).
Anyway, we can refer to the common structure of many system engineer EU regulations that are publicly available (such as the [TSI for locos and passengers trains](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32014R1302&qid=1650928937227&from=EN)).
 
For example, in the following screenshot I've tried to highlight the main items in a random section of the document.

![image](https://user-images.githubusercontent.com/7449970/165191113-a64e7d92-69fe-4ab9-a4c7-77606ee16ff4.png)

Referring to the above screenshot, each list item is in fact a requirement that should be managed separately.

Each requirement have an UID. In the example, the UID is defined by the section number and the list number.
Anyway, I would avoid implementing a function to automatically define the requirement UID starting from the document structure. StrictDoc already allows to define custom UID and that is enough.

More in general, from my personal viewpoint, I consider the UID as a mandatory attribute for a requirement: if there is no UID, we are dealing with free/informative text only.
Please consider that (for my use case) requirements are managed following the general V-Model lifecycle, so linking (and thus UIDs) are necessary.  

> Currently StrictDoc shows a requirement's UID in the TOC if the requirement does not have a title. Is this behaviour acceptable or you want to remove it from TOC completely?

I would prefer to completely remove the unnumbered/untitled requirements from TOC and limiting the TOC contents to the document's structure items (i.e. sections). In my opinion, this makes easier to read the TOC when dealing with a large number of untitled requirements.

> I am checking this now in the current StrictDoc's UI - if I completely remove the title from the requirement template (`h_title.jinja.html`), the template does not look great, this is why I would like to see your example to get an idea of how we should present this UI-wise (this is where I might again ask @mettta for help).

A proposal for the UI representation, could be to render the `requirement_meta` grid (at least for the UID part) as a side note in document view, likewise is done for table view. Honestly, I don't know if the same strategy should be applied to all the attributes included in the `requirement_meta` grid, since too long side notes could affect the readability of the document.

**Comment by stanislaw** [comment]
Hi @gioboske,

Here's a small update. @mettta and I are discussing how we would implement this "requirements with no titles" aspect as well as some items from https://github.com/strictdoc-project/strictdoc/discussions/621. Overall, it looks like we need one or two iterations before we can get to something release-able, I estimate this will take 1-2 weeks. Stay tuned.

**Comment by stanislaw** [comment]
@mettta and I are 50% through on the way to implementing this. The estimate is still 1-2 weeks :smile: Stay tuned.

**Comment by stanislaw** [comment]
The test version is released here: https://test.pypi.org/project/strictdoc/0.0.26a1/.

@mettta and I believe that we could simplify the implementation:

Now, StrictDoc no longer attempts to do any "No Title". Instead the rule is simply show the title when it's there and don't when it is not. On top of that there is now an option that allows you to remove the requirement titles from TOC: https://strictdoc.readthedocs.io/en/latest/strictdoc-1-user-manual.html#option-requirement-title-in-table-of-contents.

I will close this ticket but feel free to reopen it if you find any issues during testing.

**Comment by gioboske** [comment]
Thank you for the update!
I will perform some tests on version 0.0.26a1 and I'll let you know.

**Comment by stanislaw** [comment]
@BenGardiner a small heads-up: in your current export https://nmfta-repo.github.io/vcr-experiment/vcr-experiment/00_tsrm.html, the table of contents contains the UIDs of all requirements.

Please note that we have removed this behavior to simplify how the requirement titles are handled (see the discussion of this ticket).

Here's one example where and how we have removed this: https://github.com/strictdoc-project/strictdoc/pull/701/files#diff-ddbadf990ac6f83c25d4ef48184323a0fff8245075c5a5fb7e7fecdc9af951aeL4.

Please confirm that this behavior does not go against your expectations, I just re-generated your requirements data locally:

![Uploading Bildschirmfoto 2022-05-15 um 22.09.27.png…]()

**Comment by stanislaw** [comment]
In case, if anyone needs the UIDs to be printed as requirement titles, we will have to consider three cases:

1) Default one: Requirements always have TITLE field and their titles are displayed in the table of contents and requirements headers.

2) Requirements do not have TITLE field - they are not displayed in the TOC and do not appear as title headers (it is implemented like this now).

3) Requirements do not have TITLE but someone would prefer to see the UIDs to be titles in the TOC and requirements titles. It used to be almost like this but was conflicting with what has been requested in this ticket by me and @gioboske.

Looking forward to feedback.

**Comment by BenGardiner** [comment]
@stanislaw yes I think we can live without the UIDs as titles. The change has hit our main https://nmfta-repo.github.io/vcr-experiment/vcr-experiment/00_tsrm.html and I think it looks fine.

**Comment by stanislaw** [comment]
> @stanislaw yes I think we can live without the UIDs as titles. The change has hit our main https://nmfta-repo.github.io/vcr-experiment/vcr-experiment/00_tsrm.html and I think it looks fine.

Ok, thanks!
