### ISSUE TITLE
Reference to grammar in docs is broken

### ISSUE THREAD

**Issue by fkromer** [strictdoc-project/strictdoc#564]
The reference [`grammar.py` in the docs](https://strictdoc.readthedocs.io/en/stable/strictdoc.html#sdoc-syntax) to [here](https://github.com/strictdoc-project/strictdoc/blob/main/strictdoc/backend/dsl/grammar.py) is dead.

**Comment by stanislaw** [comment]
Good catch. This is a result of some Christmas work :)

Are you by any chance aware of a good dead links checker in Python? It's been a while that I wanted to write one because the one I have been using for awesome-safety-critical does not always do what I want: https://github.com/dkhamsing/awesome_bot.
