### ISSUE TITLE
ReqIF: implement export of composite requirements

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#812]
```
NotImplementedError: ('Exporting composite requirements is not supported yet.', CompositeRequirement(requirement_type = "REQUIREMENT", fields = [2 elements], requirements = [3 elements], _tx_position = 2055, _tx_position_end = 2447, parent = Section(...), uid = NoneType(...), level = NoneType(...), status = NoneType(...), tags = NoneType(...), references = [], title = "Platform support", statement = "StrictDoc shall work on all major platforms.", rationale = NoneType(...), comments = [], statement_multiline = NoneType(...), rationale_multiline = NoneType(...), has_meta = False, fields_as_parsed = [2 elements], ordered_fields_lookup = OrderedDict(2 elements), ng_level = 2, ng_document_reference = DocumentReference(...), context = RequirementContext(...), node_id = "b8b6593ab62f4124ba4d441f9bdfc363", ng_has_requirements = True))
INFO:     connection closed
```

**Comment by stanislaw** [comment]
In https://github.com/strictdoc-project/strictdoc/pull/881, we have removed the few composite requirements from StrictDoc's own documentation which means there is no pressing need to find a way to export composite requirements to ReqIF.

Due to the nested structure of a composite requirement, it is not clear how to build a bi-directional mapping between SDoc and ReqIF because the concept of a "composite requirement" doesn't seem to exist in ReqIF.

I will close ticket as "won't fix" but it can be reopened in case there is a real need and a good implementation strategy.
