### ISSUE TITLE
Problems with pyinstaller version (OS X)

### ISSUE THREAD

**Issue by RobertoBagnara** [strictdoc-project/strictdoc#837]
The version produced with `invoke release-pyinstaller` with the unmodified sources in branch main as of today, when invoked without arguments returns the prompt and keeps printing the usage string forever:

```
usage: strictdoc [-h]
                 {about,export,import,passthrough,dump-grammar,server,version}
                 ...
strictdoc: error: the following arguments are required: command

Further help:
'strictdoc -h/--help' provides a general overview of available commands.
'strictdoc <command> -h/--help' provides command-specific help.
```

**Comment by RobertoBagnara** [comment]
A useful information might be given by the output of `ps`:

```
4424 s001  R      0:00.24 /private/tmp/strictdoc/strictdoc/strictdoc -B -S -E -s -c from multiprocessing.resource_tracker import main;main(7)
```

One such process is spawned around once per second.

**Comment by stanislaw** [comment]
I cannot reproduce this on my macOS and the integration test job on macOS is passing. It looks like you have to dig deeper to investigate what's happening out there.

I would start with understanding:

- Which Python version
- Which PyInstaller version
- Which macOS version just in case.

and start googling for something similar with regards to PyInstaller and `argparse` which is a very standard library for parsing CLI arguments that StrictDoc uses. I suspect that the problem is within PyInstaller magic, and I cannot investigate it without more details.

**Comment by stanislaw** [comment]
Actually, the nightly job showed me that the PyInstaller hangs. An example: https://github.com/strictdoc-project/strictdoc/actions/runs/4009277695/jobs/6884437759.

**Comment by stanislaw** [comment]
I have tried to make an alternative solution work: https://github.com/strictdoc-project/strictdoc/discussions/842, and compiling with Nuitra also produces binaries that either crash or miss symbols in the Python dynamic libraries.

I am not decided yet, if I should take to roll up my sleeves and troubleshoot either of these solutions or let someone else like your team @RobertoBagnara to work on this.

**Comment by RobertoBagnara** [comment]
I filed a PyInstaller issue here: [https://github.com/pyinstaller/pyinstaller/issues/7438](url)
